apiVersion: v1
kind: ConfigMap
metadata:
  name: vanshapp-config
  labels:
    app: vanshapp
    owner: vansh
data:
  APP_NAME: "Vansh App"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  PORT: "8080"
  DEFAULT_CURRENCY: "INR"
