apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-stateful
  labels:
    owner: vansh
spec:
  serviceName: web-service-headless
  replicas: 3
  selector:
    matchLabels:
      app: web-headless
  template:
    metadata:
      labels:
        app: web-headless
        owner: vansh
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
              name: http
